name = "ecommerce-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 简化配置，先不使用KV和R2
# 只使用D1数据库进行基本功能测试

# 环境变量
[vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:5174"
JWT_SECRET = "your-jwt-secret-key-here"

# 如果有D1数据库ID，取消注释下面的配置
# [[d1_databases]]
# binding = "DB"
# database_name = "ecommerce-db"
# database_id = "your-database-id"